# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alpha_ui.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1109, 927)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout.addWidget(self.verticalScrollBar, 0, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.characterSheet_tb = QtWidgets.QWidget()
        self.characterSheet_tb.setObjectName("characterSheet_tb")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.characterSheet_tb)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 221, 73))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.characterName_hl = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.characterName_hl.setContentsMargins(0, 0, 0, 0)
        self.characterName_hl.setObjectName("characterName_hl")
        self.characterName_lb = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.characterName_lb.setObjectName("characterName_lb")
        self.characterName_hl.addWidget(self.characterName_lb)
        self.characterName_le = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.characterName_le.setObjectName("characterName_le")
        self.characterName_hl.addWidget(self.characterName_le)
        self.characterName_vertline = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.characterName_vertline.setFrameShape(QtWidgets.QFrame.VLine)
        self.characterName_vertline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.characterName_vertline.setObjectName("characterName_vertline")
        self.characterName_hl.addWidget(self.characterName_vertline)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.characterSheet_tb)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 61, 443))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.attributes_vl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.attributes_vl.setContentsMargins(0, 0, 0, 0)
        self.attributes_vl.setObjectName("attributes_vl")
        self.attrTop_horzline = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.attrTop_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.attrTop_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.attrTop_horzline.setObjectName("attrTop_horzline")
        self.attributes_vl.addWidget(self.attrTop_horzline)
        self.strength_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.strength_lb.setObjectName("strength_lb")
        self.attributes_vl.addWidget(self.strength_lb, QtCore.Qt.AlignHCenter)
        self.strength_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.strength_sb.setObjectName("strength_sb")
        self.attributes_vl.addWidget(self.strength_sb, QtCore.Qt.AlignHCenter)
        self.strMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.strMod_lb.setObjectName("strMod_lb")
        self.attributes_vl.addWidget(self.strMod_lb, QtCore.Qt.AlignHCenter)
        self.str_horzline = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.str_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.str_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.str_horzline.setObjectName("str_horzline")
        self.attributes_vl.addWidget(self.str_horzline)
        self.dexterity_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dexterity_lb.setObjectName("dexterity_lb")
        self.attributes_vl.addWidget(self.dexterity_lb, QtCore.Qt.AlignHCenter)
        self.dexterity_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.dexterity_sb.setObjectName("dexterity_sb")
        self.attributes_vl.addWidget(self.dexterity_sb, QtCore.Qt.AlignHCenter)
        self.dexMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dexMod_lb.setObjectName("dexMod_lb")
        self.attributes_vl.addWidget(self.dexMod_lb, QtCore.Qt.AlignHCenter)
        self.dex_horzline = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.dex_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.dex_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dex_horzline.setObjectName("dex_horzline")
        self.attributes_vl.addWidget(self.dex_horzline)
        self.constitutuion_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.constitutuion_lb.setObjectName("constitutuion_lb")
        self.attributes_vl.addWidget(self.constitutuion_lb, QtCore.Qt.AlignHCenter)
        self.constitution_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.constitution_sb.setObjectName("constitution_sb")
        self.attributes_vl.addWidget(self.constitution_sb, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.conMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.conMod_lb.setObjectName("conMod_lb")
        self.attributes_vl.addWidget(self.conMod_lb, QtCore.Qt.AlignHCenter)
        self.con_horzline = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.con_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.con_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.con_horzline.setObjectName("con_horzline")
        self.attributes_vl.addWidget(self.con_horzline)
        self.intelligence_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.intelligence_lb.setObjectName("intelligence_lb")
        self.attributes_vl.addWidget(self.intelligence_lb, QtCore.Qt.AlignHCenter)
        self.intelligence_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.intelligence_sb.setObjectName("intelligence_sb")
        self.attributes_vl.addWidget(self.intelligence_sb, QtCore.Qt.AlignHCenter)
        self.intMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.intMod_lb.setObjectName("intMod_lb")
        self.attributes_vl.addWidget(self.intMod_lb, QtCore.Qt.AlignHCenter)
        self.int_horzline = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.int_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.int_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.int_horzline.setObjectName("int_horzline")
        self.attributes_vl.addWidget(self.int_horzline)
        self.wisdom_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.wisdom_lb.setObjectName("wisdom_lb")
        self.attributes_vl.addWidget(self.wisdom_lb, QtCore.Qt.AlignHCenter)
        self.wisdom_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.wisdom_sb.setObjectName("wisdom_sb")
        self.attributes_vl.addWidget(self.wisdom_sb, QtCore.Qt.AlignHCenter)
        self.wisMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.wisMod_lb.setObjectName("wisMod_lb")
        self.attributes_vl.addWidget(self.wisMod_lb, QtCore.Qt.AlignHCenter)
        self.wis_horzline = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.wis_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.wis_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.wis_horzline.setObjectName("wis_horzline")
        self.attributes_vl.addWidget(self.wis_horzline)
        self.charisma_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.charisma_lb.setObjectName("charisma_lb")
        self.attributes_vl.addWidget(self.charisma_lb, QtCore.Qt.AlignHCenter)
        self.charisma_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.charisma_sb.setObjectName("charisma_sb")
        self.attributes_vl.addWidget(self.charisma_sb, QtCore.Qt.AlignHCenter)
        self.chaMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.chaMod_lb.setObjectName("chaMod_lb")
        self.attributes_vl.addWidget(self.chaMod_lb, QtCore.Qt.AlignHCenter)
        self.attrBot_horzline = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.attrBot_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.attrBot_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.attrBot_horzline.setObjectName("attrBot_horzline")
        self.attributes_vl.addWidget(self.attrBot_horzline)
        self.randomize_btn = QtWidgets.QPushButton(self.characterSheet_tb)
        self.randomize_btn.setGeometry(QtCore.QRect(10, 540, 61, 23))
        self.randomize_btn.setObjectName("randomize_btn")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.characterSheet_tb)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(80, 90, 181, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.savingThrows_vl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.savingThrows_vl.setContentsMargins(0, 0, 0, 0)
        self.savingThrows_vl.setObjectName("savingThrows_vl")
        self.savingThrowsTop_horzline = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.savingThrowsTop_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.savingThrowsTop_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.savingThrowsTop_horzline.setObjectName("savingThrowsTop_horzline")
        self.savingThrows_vl.addWidget(self.savingThrowsTop_horzline)
        self.strengthSavingThrow_hl = QtWidgets.QHBoxLayout()
        self.strengthSavingThrow_hl.setObjectName("strengthSavingThrow_hl")
        self.strengthSavingThrow_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.strengthSavingThrow_cb.setObjectName("strengthSavingThrow_cb")
        self.strengthSavingThrow_hl.addWidget(self.strengthSavingThrow_cb, QtCore.Qt.AlignHCenter)
        self.strengthSavingThrow_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.strengthSavingThrow_sb.setObjectName("strengthSavingThrow_sb")
        self.strengthSavingThrow_hl.addWidget(self.strengthSavingThrow_sb, QtCore.Qt.AlignHCenter)
        self.strengthSavingThrow_lb = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.strengthSavingThrow_lb.setObjectName("strengthSavingThrow_lb")
        self.strengthSavingThrow_hl.addWidget(self.strengthSavingThrow_lb, QtCore.Qt.AlignHCenter)
        self.savingThrows_vl.addLayout(self.strengthSavingThrow_hl)
        self.dexteritySavingThrow_hl = QtWidgets.QHBoxLayout()
        self.dexteritySavingThrow_hl.setObjectName("dexteritySavingThrow_hl")
        self.dexteritySavingThrow_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.dexteritySavingThrow_cb.setObjectName("dexteritySavingThrow_cb")
        self.dexteritySavingThrow_hl.addWidget(self.dexteritySavingThrow_cb, QtCore.Qt.AlignHCenter)
        self.dexteritySavingThrow_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.dexteritySavingThrow_sb.setObjectName("dexteritySavingThrow_sb")
        self.dexteritySavingThrow_hl.addWidget(self.dexteritySavingThrow_sb, QtCore.Qt.AlignHCenter)
        self.dexteritySavingThrow_lb = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.dexteritySavingThrow_lb.setObjectName("dexteritySavingThrow_lb")
        self.dexteritySavingThrow_hl.addWidget(self.dexteritySavingThrow_lb)
        self.savingThrows_vl.addLayout(self.dexteritySavingThrow_hl)
        self.constitutionSavingThrow_hl = QtWidgets.QHBoxLayout()
        self.constitutionSavingThrow_hl.setObjectName("constitutionSavingThrow_hl")
        self.constitutionSavingThrow_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.constitutionSavingThrow_cb.setObjectName("constitutionSavingThrow_cb")
        self.constitutionSavingThrow_hl.addWidget(self.constitutionSavingThrow_cb, QtCore.Qt.AlignHCenter)
        self.constitutionSavingThrow_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.constitutionSavingThrow_sb.setObjectName("constitutionSavingThrow_sb")
        self.constitutionSavingThrow_hl.addWidget(self.constitutionSavingThrow_sb, QtCore.Qt.AlignHCenter)
        self.constitutionSavingThrow_lb = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.constitutionSavingThrow_lb.setObjectName("constitutionSavingThrow_lb")
        self.constitutionSavingThrow_hl.addWidget(self.constitutionSavingThrow_lb, QtCore.Qt.AlignHCenter)
        self.savingThrows_vl.addLayout(self.constitutionSavingThrow_hl)
        self.intelligenceSavingThrow_hl = QtWidgets.QHBoxLayout()
        self.intelligenceSavingThrow_hl.setObjectName("intelligenceSavingThrow_hl")
        self.intelligenceSavingThrow_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.intelligenceSavingThrow_cb.setObjectName("intelligenceSavingThrow_cb")
        self.intelligenceSavingThrow_hl.addWidget(self.intelligenceSavingThrow_cb, QtCore.Qt.AlignHCenter)
        self.intelligenceSavingThrow_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.intelligenceSavingThrow_sb.setObjectName("intelligenceSavingThrow_sb")
        self.intelligenceSavingThrow_hl.addWidget(self.intelligenceSavingThrow_sb, QtCore.Qt.AlignHCenter)
        self.intelligenceSavingThrow_lb = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.intelligenceSavingThrow_lb.setObjectName("intelligenceSavingThrow_lb")
        self.intelligenceSavingThrow_hl.addWidget(self.intelligenceSavingThrow_lb, QtCore.Qt.AlignHCenter)
        self.savingThrows_vl.addLayout(self.intelligenceSavingThrow_hl)
        self.wisdomSavingThrow_hl = QtWidgets.QHBoxLayout()
        self.wisdomSavingThrow_hl.setObjectName("wisdomSavingThrow_hl")
        self.wisdomSavingThrow_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.wisdomSavingThrow_cb.setObjectName("wisdomSavingThrow_cb")
        self.wisdomSavingThrow_hl.addWidget(self.wisdomSavingThrow_cb, QtCore.Qt.AlignHCenter)
        self.wisdomSavingThrow_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.wisdomSavingThrow_sb.setObjectName("wisdomSavingThrow_sb")
        self.wisdomSavingThrow_hl.addWidget(self.wisdomSavingThrow_sb, QtCore.Qt.AlignHCenter)
        self.wisdomSavingThrow_lb = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.wisdomSavingThrow_lb.setObjectName("wisdomSavingThrow_lb")
        self.wisdomSavingThrow_hl.addWidget(self.wisdomSavingThrow_lb, QtCore.Qt.AlignHCenter)
        self.savingThrows_vl.addLayout(self.wisdomSavingThrow_hl)
        self.charismaSavingThrow_hl = QtWidgets.QHBoxLayout()
        self.charismaSavingThrow_hl.setObjectName("charismaSavingThrow_hl")
        self.charismaSavingThrow_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.charismaSavingThrow_cb.setObjectName("charismaSavingThrow_cb")
        self.charismaSavingThrow_hl.addWidget(self.charismaSavingThrow_cb, QtCore.Qt.AlignHCenter)
        self.charismaSavingThrow_sb = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.charismaSavingThrow_sb.setObjectName("charismaSavingThrow_sb")
        self.charismaSavingThrow_hl.addWidget(self.charismaSavingThrow_sb, QtCore.Qt.AlignHCenter)
        self.charismaSavingThrow_lb = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.charismaSavingThrow_lb.setObjectName("charismaSavingThrow_lb")
        self.charismaSavingThrow_hl.addWidget(self.charismaSavingThrow_lb, QtCore.Qt.AlignHCenter)
        self.savingThrows_vl.addLayout(self.charismaSavingThrow_hl)
        self.savingThrowsBottom_horzline = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.savingThrowsBottom_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.savingThrowsBottom_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.savingThrowsBottom_horzline.setObjectName("savingThrowsBottom_horzline")
        self.savingThrows_vl.addWidget(self.savingThrowsBottom_horzline)
        self.savingThrows_lb = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.savingThrows_lb.setObjectName("savingThrows_lb")
        self.savingThrows_vl.addWidget(self.savingThrows_lb, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.characterSheet_tb)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(310, 230, 221, 81))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.deathSaves_vl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.deathSaves_vl.setContentsMargins(0, 0, 0, 0)
        self.deathSaves_vl.setObjectName("deathSaves_vl")
        self.deathSavesTop_horzline = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.deathSavesTop_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.deathSavesTop_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.deathSavesTop_horzline.setObjectName("deathSavesTop_horzline")
        self.deathSaves_vl.addWidget(self.deathSavesTop_horzline)
        self.successes_vl = QtWidgets.QVBoxLayout()
        self.successes_vl.setObjectName("successes_vl")
        self.successes_hl = QtWidgets.QHBoxLayout()
        self.successes_hl.setObjectName("successes_hl")
        self.successes_lb = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.successes_lb.setObjectName("successes_lb")
        self.successes_hl.addWidget(self.successes_lb)
        self.successes1_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        self.successes1_cb.setText("")
        self.successes1_cb.setObjectName("successes1_cb")
        self.successes_hl.addWidget(self.successes1_cb)
        self.successes2_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        self.successes2_cb.setText("")
        self.successes2_cb.setObjectName("successes2_cb")
        self.successes_hl.addWidget(self.successes2_cb)
        self.successes3_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        self.successes3_cb.setText("")
        self.successes3_cb.setObjectName("successes3_cb")
        self.successes_hl.addWidget(self.successes3_cb)
        self.successes_vl.addLayout(self.successes_hl)
        self.deathSaves_vl.addLayout(self.successes_vl)
        self.failures_vl = QtWidgets.QVBoxLayout()
        self.failures_vl.setObjectName("failures_vl")
        self.failures_hl = QtWidgets.QHBoxLayout()
        self.failures_hl.setObjectName("failures_hl")
        self.failures_hl_2 = QtWidgets.QHBoxLayout()
        self.failures_hl_2.setObjectName("failures_hl_2")
        self.failures_lb = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.failures_lb.setObjectName("failures_lb")
        self.failures_hl_2.addWidget(self.failures_lb)
        self.failures1_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        self.failures1_cb.setText("")
        self.failures1_cb.setObjectName("failures1_cb")
        self.failures_hl_2.addWidget(self.failures1_cb)
        self.failures2_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        self.failures2_cb.setText("")
        self.failures2_cb.setObjectName("failures2_cb")
        self.failures_hl_2.addWidget(self.failures2_cb)
        self.failures3_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_8)
        self.failures3_cb.setText("")
        self.failures3_cb.setObjectName("failures3_cb")
        self.failures_hl_2.addWidget(self.failures3_cb)
        self.failures_hl.addLayout(self.failures_hl_2)
        self.failures_vl.addLayout(self.failures_hl)
        self.deathSaves_vl.addLayout(self.failures_vl)
        self.deathSavesBottom_horzline = QtWidgets.QFrame(self.verticalLayoutWidget_8)
        self.deathSavesBottom_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.deathSavesBottom_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.deathSavesBottom_horzline.setObjectName("deathSavesBottom_horzline")
        self.deathSaves_vl.addWidget(self.deathSavesBottom_horzline)
        self.deathSaves_lb = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.deathSaves_lb.setObjectName("deathSaves_lb")
        self.deathSaves_vl.addWidget(self.deathSaves_lb, QtCore.Qt.AlignHCenter)
        self.gridLayoutWidget = QtWidgets.QWidget(self.characterSheet_tb)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(260, 10, 443, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.top_info_gl = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.top_info_gl.setContentsMargins(0, 0, 0, 0)
        self.top_info_gl.setObjectName("top_info_gl")
        self.class_hl = QtWidgets.QHBoxLayout()
        self.class_hl.setObjectName("class_hl")
        self.class_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.class_lb.setObjectName("class_lb")
        self.class_hl.addWidget(self.class_lb)
        self.class_combo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.class_combo.setObjectName("class_combo")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_combo.addItem("")
        self.class_hl.addWidget(self.class_combo)
        self.background_hl = QtWidgets.QHBoxLayout()
        self.background_hl.setObjectName("background_hl")
        self.background_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.background_lb.setObjectName("background_lb")
        self.background_hl.addWidget(self.background_lb)
        self.background_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.background_le.setObjectName("background_le")
        self.background_hl.addWidget(self.background_le)
        self.playerName_hl = QtWidgets.QHBoxLayout()
        self.playerName_hl.setObjectName("playerName_hl")
        self.playerName_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.playerName_lb.setObjectName("playerName_lb")
        self.playerName_hl.addWidget(self.playerName_lb)
        self.playerName_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.playerName_le.setObjectName("playerName_le")
        self.playerName_hl.addWidget(self.playerName_le)
        self.background_hl.addLayout(self.playerName_hl)
        self.class_hl.addLayout(self.background_hl)
        self.top_info_gl.addLayout(self.class_hl, 0, 0, 1, 1)
        self.race_hl = QtWidgets.QHBoxLayout()
        self.race_hl.setObjectName("race_hl")
        self.race_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.race_lb.setObjectName("race_lb")
        self.race_hl.addWidget(self.race_lb)
        self.race_combo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.race_combo.setObjectName("race_combo")
        self.race_combo.addItem("")
        self.race_combo.addItem("")
        self.race_combo.addItem("")
        self.race_combo.addItem("")
        self.race_combo.addItem("")
        self.race_combo.addItem("")
        self.race_combo.addItem("")
        self.race_combo.addItem("")
        self.race_combo.addItem("")
        self.race_hl.addWidget(self.race_combo)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.alignment_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.alignment_lb.setObjectName("alignment_lb")
        self.horizontalLayout_5.addWidget(self.alignment_lb)
        self.alignment_combo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.alignment_combo.setObjectName("alignment_combo")
        self.alignment_combo.addItem("")
        self.alignment_combo.addItem("")
        self.alignment_combo.addItem("")
        self.alignment_combo.addItem("")
        self.alignment_combo.addItem("")
        self.alignment_combo.addItem("")
        self.alignment_combo.addItem("")
        self.alignment_combo.addItem("")
        self.alignment_combo.addItem("")
        self.horizontalLayout_5.addWidget(self.alignment_combo)
        self.xp_hl = QtWidgets.QHBoxLayout()
        self.xp_hl.setObjectName("xp_hl")
        self.xp_lb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.xp_lb.setObjectName("xp_lb")
        self.xp_hl.addWidget(self.xp_lb)
        self.xp_le = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.xp_le.setObjectName("xp_le")
        self.xp_hl.addWidget(self.xp_le)
        self.horizontalLayout_5.addLayout(self.xp_hl)
        self.race_hl.addLayout(self.horizontalLayout_5)
        self.top_info_gl.addLayout(self.race_hl, 1, 0, 1, 1)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.characterSheet_tb)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(270, 100, 301, 112))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.defense_vl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.defense_vl.setContentsMargins(0, 0, 0, 0)
        self.defense_vl.setObjectName("defense_vl")
        self.defenseTop_horzline = QtWidgets.QFrame(self.verticalLayoutWidget_18)
        self.defenseTop_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.defenseTop_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.defenseTop_horzline.setObjectName("defenseTop_horzline")
        self.defense_vl.addWidget(self.defenseTop_horzline)
        self.defenseTop_gl = QtWidgets.QGridLayout()
        self.defenseTop_gl.setObjectName("defenseTop_gl")
        self.armorClass_vl = QtWidgets.QVBoxLayout()
        self.armorClass_vl.setObjectName("armorClass_vl")
        self.armorClass_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.armorClass_le.setObjectName("armorClass_le")
        self.armorClass_vl.addWidget(self.armorClass_le)
        self.armorClass_lb = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.armorClass_lb.setObjectName("armorClass_lb")
        self.armorClass_vl.addWidget(self.armorClass_lb, QtCore.Qt.AlignHCenter)
        self.defenseTop_gl.addLayout(self.armorClass_vl, 0, 0, 1, 1)
        self.initiative_vl = QtWidgets.QVBoxLayout()
        self.initiative_vl.setObjectName("initiative_vl")
        self.initiative_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.initiative_le.setObjectName("initiative_le")
        self.initiative_vl.addWidget(self.initiative_le)
        self.initiative_lb = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.initiative_lb.setObjectName("initiative_lb")
        self.initiative_vl.addWidget(self.initiative_lb, QtCore.Qt.AlignHCenter)
        self.defenseTop_gl.addLayout(self.initiative_vl, 0, 1, 1, 1)
        self.speed_vl = QtWidgets.QVBoxLayout()
        self.speed_vl.setObjectName("speed_vl")
        self.speed_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.speed_le.setObjectName("speed_le")
        self.speed_vl.addWidget(self.speed_le)
        self.speed_lb = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.speed_lb.setObjectName("speed_lb")
        self.speed_vl.addWidget(self.speed_lb, QtCore.Qt.AlignHCenter)
        self.defenseTop_gl.addLayout(self.speed_vl, 0, 2, 1, 1)
        self.defense_vl.addLayout(self.defenseTop_gl)
        self.defenseBot_hl = QtWidgets.QHBoxLayout()
        self.defenseBot_hl.setObjectName("defenseBot_hl")
        self.currentHP_vl = QtWidgets.QVBoxLayout()
        self.currentHP_vl.setObjectName("currentHP_vl")
        self.currentHP_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.currentHP_le.setObjectName("currentHP_le")
        self.currentHP_vl.addWidget(self.currentHP_le)
        self.currentHP_lb = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.currentHP_lb.setObjectName("currentHP_lb")
        self.currentHP_vl.addWidget(self.currentHP_lb, QtCore.Qt.AlignHCenter)
        self.defenseBot_hl.addLayout(self.currentHP_vl)
        self.totalHitDice_vl = QtWidgets.QVBoxLayout()
        self.totalHitDice_vl.setObjectName("totalHitDice_vl")
        self.totalHitDice_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.totalHitDice_le.setObjectName("totalHitDice_le")
        self.totalHitDice_vl.addWidget(self.totalHitDice_le)
        self.totalHitDice_lb = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.totalHitDice_lb.setObjectName("totalHitDice_lb")
        self.totalHitDice_vl.addWidget(self.totalHitDice_lb, QtCore.Qt.AlignHCenter)
        self.defenseBot_hl.addLayout(self.totalHitDice_vl)
        self.hitDice_vl = QtWidgets.QVBoxLayout()
        self.hitDice_vl.setObjectName("hitDice_vl")
        self.hitDice_le = QtWidgets.QLineEdit(self.verticalLayoutWidget_18)
        self.hitDice_le.setObjectName("hitDice_le")
        self.hitDice_vl.addWidget(self.hitDice_le)
        self.hitDice_lb = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.hitDice_lb.setObjectName("hitDice_lb")
        self.hitDice_vl.addWidget(self.hitDice_lb, QtCore.Qt.AlignHCenter)
        self.defenseBot_hl.addLayout(self.hitDice_vl)
        self.defense_vl.addLayout(self.defenseBot_hl)
        self.defenseBot_horzline = QtWidgets.QFrame(self.verticalLayoutWidget_18)
        self.defenseBot_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.defenseBot_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.defenseBot_horzline.setObjectName("defenseBot_horzline")
        self.defense_vl.addWidget(self.defenseBot_horzline)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.characterSheet_tb)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(90, 290, 160, 410))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.skill_vl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.skill_vl.setContentsMargins(0, 0, 0, 0)
        self.skill_vl.setObjectName("skill_vl")
        self.skill_fl = QtWidgets.QFormLayout()
        self.skill_fl.setObjectName("skill_fl")
        self.acrobatics_hl = QtWidgets.QHBoxLayout()
        self.acrobatics_hl.setObjectName("acrobatics_hl")
        self.acrobatics_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.acrobatics_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.acrobatics_cb.setText("")
        self.acrobatics_cb.setObjectName("acrobatics_cb")
        self.acrobatics_hl.addWidget(self.acrobatics_cb)
        self.acrobaticsMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.acrobaticsMod_lb.setObjectName("acrobaticsMod_lb")
        self.acrobatics_hl.addWidget(self.acrobaticsMod_lb)
        self.skill_fl.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.acrobatics_hl)
        self.acrobatics_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.acrobatics_lb.setObjectName("acrobatics_lb")
        self.skill_fl.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.acrobatics_lb)
        self.animalHandling_hl = QtWidgets.QHBoxLayout()
        self.animalHandling_hl.setObjectName("animalHandling_hl")
        self.animalHandling_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.animalHandling_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.animalHandling_cb.setText("")
        self.animalHandling_cb.setObjectName("animalHandling_cb")
        self.animalHandling_hl.addWidget(self.animalHandling_cb)
        self.animalHandlingMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.animalHandlingMod_lb.setObjectName("animalHandlingMod_lb")
        self.animalHandling_hl.addWidget(self.animalHandlingMod_lb)
        self.skill_fl.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.animalHandling_hl)
        self.animalHandling_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.animalHandling_lb.setObjectName("animalHandling_lb")
        self.skill_fl.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.animalHandling_lb)
        self.arcana_hl = QtWidgets.QHBoxLayout()
        self.arcana_hl.setObjectName("arcana_hl")
        self.arcana_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.arcana_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.arcana_cb.setText("")
        self.arcana_cb.setObjectName("arcana_cb")
        self.arcana_hl.addWidget(self.arcana_cb)
        self.arcanaMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.arcanaMod_lb.setObjectName("arcanaMod_lb")
        self.arcana_hl.addWidget(self.arcanaMod_lb)
        self.skill_fl.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.arcana_hl)
        self.arcana_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.arcana_lb.setObjectName("arcana_lb")
        self.skill_fl.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.arcana_lb)
        self.athletics_hl = QtWidgets.QHBoxLayout()
        self.athletics_hl.setObjectName("athletics_hl")
        self.athletics_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.athletics_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.athletics_cb.setText("")
        self.athletics_cb.setObjectName("athletics_cb")
        self.athletics_hl.addWidget(self.athletics_cb)
        self.athleticsMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.athleticsMod_lb.setObjectName("athleticsMod_lb")
        self.athletics_hl.addWidget(self.athleticsMod_lb)
        self.skill_fl.setLayout(3, QtWidgets.QFormLayout.LabelRole, self.athletics_hl)
        self.atheltics_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.atheltics_lb.setObjectName("atheltics_lb")
        self.skill_fl.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.atheltics_lb)
        self.deception_hl = QtWidgets.QHBoxLayout()
        self.deception_hl.setObjectName("deception_hl")
        self.deception_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.deception_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.deception_cb.setText("")
        self.deception_cb.setObjectName("deception_cb")
        self.deception_hl.addWidget(self.deception_cb)
        self.deceptionMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.deceptionMod_lb.setObjectName("deceptionMod_lb")
        self.deception_hl.addWidget(self.deceptionMod_lb)
        self.skill_fl.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.deception_hl)
        self.deception_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.deception_lb.setObjectName("deception_lb")
        self.skill_fl.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.deception_lb)
        self.history_hl = QtWidgets.QHBoxLayout()
        self.history_hl.setObjectName("history_hl")
        self.history_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.history_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.history_cb.setText("")
        self.history_cb.setObjectName("history_cb")
        self.history_hl.addWidget(self.history_cb)
        self.historyMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.historyMod_lb.setObjectName("historyMod_lb")
        self.history_hl.addWidget(self.historyMod_lb)
        self.skill_fl.setLayout(5, QtWidgets.QFormLayout.LabelRole, self.history_hl)
        self.history_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.history_lb.setObjectName("history_lb")
        self.skill_fl.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.history_lb)
        self.insight_hl = QtWidgets.QHBoxLayout()
        self.insight_hl.setObjectName("insight_hl")
        self.insight_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.insight_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.insight_cb.setText("")
        self.insight_cb.setObjectName("insight_cb")
        self.insight_hl.addWidget(self.insight_cb)
        self.insightMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.insightMod_lb.setObjectName("insightMod_lb")
        self.insight_hl.addWidget(self.insightMod_lb)
        self.skill_fl.setLayout(6, QtWidgets.QFormLayout.LabelRole, self.insight_hl)
        self.insight_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.insight_lb.setObjectName("insight_lb")
        self.skill_fl.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.insight_lb)
        self.intimidation_hl = QtWidgets.QHBoxLayout()
        self.intimidation_hl.setObjectName("intimidation_hl")
        self.intimidation_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.intimidation_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.intimidation_cb.setText("")
        self.intimidation_cb.setObjectName("intimidation_cb")
        self.intimidation_hl.addWidget(self.intimidation_cb)
        self.intimidationMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.intimidationMod_lb.setObjectName("intimidationMod_lb")
        self.intimidation_hl.addWidget(self.intimidationMod_lb)
        self.skill_fl.setLayout(7, QtWidgets.QFormLayout.LabelRole, self.intimidation_hl)
        self.intimidation_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.intimidation_lb.setObjectName("intimidation_lb")
        self.skill_fl.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.intimidation_lb)
        self.investigation_hl = QtWidgets.QHBoxLayout()
        self.investigation_hl.setObjectName("investigation_hl")
        self.investigation_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.investigation_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.investigation_cb.setText("")
        self.investigation_cb.setObjectName("investigation_cb")
        self.investigation_hl.addWidget(self.investigation_cb)
        self.investigationMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.investigationMod_lb.setObjectName("investigationMod_lb")
        self.investigation_hl.addWidget(self.investigationMod_lb)
        self.skill_fl.setLayout(8, QtWidgets.QFormLayout.LabelRole, self.investigation_hl)
        self.investigation_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.investigation_lb.setObjectName("investigation_lb")
        self.skill_fl.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.investigation_lb)
        self.medicine_hl = QtWidgets.QHBoxLayout()
        self.medicine_hl.setObjectName("medicine_hl")
        self.medicine_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.medicine_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.medicine_cb.setText("")
        self.medicine_cb.setObjectName("medicine_cb")
        self.medicine_hl.addWidget(self.medicine_cb)
        self.medicineMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.medicineMod_lb.setObjectName("medicineMod_lb")
        self.medicine_hl.addWidget(self.medicineMod_lb)
        self.skill_fl.setLayout(9, QtWidgets.QFormLayout.LabelRole, self.medicine_hl)
        self.medicine_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.medicine_lb.setObjectName("medicine_lb")
        self.skill_fl.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.medicine_lb)
        self.nature_hl = QtWidgets.QHBoxLayout()
        self.nature_hl.setObjectName("nature_hl")
        self.nature_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.nature_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.nature_cb.setText("")
        self.nature_cb.setObjectName("nature_cb")
        self.nature_hl.addWidget(self.nature_cb)
        self.natureMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.natureMod_lb.setObjectName("natureMod_lb")
        self.nature_hl.addWidget(self.natureMod_lb)
        self.skill_fl.setLayout(10, QtWidgets.QFormLayout.LabelRole, self.nature_hl)
        self.nature_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.nature_lb.setObjectName("nature_lb")
        self.skill_fl.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.nature_lb)
        self.perception_hl = QtWidgets.QHBoxLayout()
        self.perception_hl.setObjectName("perception_hl")
        self.perception_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.perception_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.perception_cb.setText("")
        self.perception_cb.setObjectName("perception_cb")
        self.perception_hl.addWidget(self.perception_cb)
        self.perceptionMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.perceptionMod_lb.setObjectName("perceptionMod_lb")
        self.perception_hl.addWidget(self.perceptionMod_lb)
        self.skill_fl.setLayout(11, QtWidgets.QFormLayout.LabelRole, self.perception_hl)
        self.perception_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.perception_lb.setObjectName("perception_lb")
        self.skill_fl.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.perception_lb)
        self.performance_hl = QtWidgets.QHBoxLayout()
        self.performance_hl.setObjectName("performance_hl")
        self.performance_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.performance_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.performance_cb.setText("")
        self.performance_cb.setObjectName("performance_cb")
        self.performance_hl.addWidget(self.performance_cb)
        self.performanceMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.performanceMod_lb.setObjectName("performanceMod_lb")
        self.performance_hl.addWidget(self.performanceMod_lb)
        self.skill_fl.setLayout(12, QtWidgets.QFormLayout.LabelRole, self.performance_hl)
        self.performance_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.performance_lb.setObjectName("performance_lb")
        self.skill_fl.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.performance_lb)
        self.persuassion_hl = QtWidgets.QHBoxLayout()
        self.persuassion_hl.setObjectName("persuassion_hl")
        self.persuassion_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.persuassion_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.persuassion_cb.setText("")
        self.persuassion_cb.setObjectName("persuassion_cb")
        self.persuassion_hl.addWidget(self.persuassion_cb)
        self.persuassionMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.persuassionMod_lb.setObjectName("persuassionMod_lb")
        self.persuassion_hl.addWidget(self.persuassionMod_lb)
        self.skill_fl.setLayout(13, QtWidgets.QFormLayout.LabelRole, self.persuassion_hl)
        self.persuassion_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.persuassion_lb.setObjectName("persuassion_lb")
        self.skill_fl.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.persuassion_lb)
        self.religion_hl = QtWidgets.QHBoxLayout()
        self.religion_hl.setObjectName("religion_hl")
        self.religion_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.religion_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.religion_cb.setText("")
        self.religion_cb.setObjectName("religion_cb")
        self.religion_hl.addWidget(self.religion_cb)
        self.religionMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.religionMod_lb.setObjectName("religionMod_lb")
        self.religion_hl.addWidget(self.religionMod_lb)
        self.skill_fl.setLayout(14, QtWidgets.QFormLayout.LabelRole, self.religion_hl)
        self.religion_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.religion_lb.setObjectName("religion_lb")
        self.skill_fl.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.religion_lb)
        self.sleightOfHand_hl = QtWidgets.QHBoxLayout()
        self.sleightOfHand_hl.setObjectName("sleightOfHand_hl")
        self.sleightOfHand_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.sleightOfHand_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.sleightOfHand_cb.setText("")
        self.sleightOfHand_cb.setObjectName("sleightOfHand_cb")
        self.sleightOfHand_hl.addWidget(self.sleightOfHand_cb)
        self.sleightOfHandMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.sleightOfHandMod_lb.setObjectName("sleightOfHandMod_lb")
        self.sleightOfHand_hl.addWidget(self.sleightOfHandMod_lb)
        self.skill_fl.setLayout(15, QtWidgets.QFormLayout.LabelRole, self.sleightOfHand_hl)
        self.sleightOfHand_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.sleightOfHand_lb.setObjectName("sleightOfHand_lb")
        self.skill_fl.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.sleightOfHand_lb)
        self.stealth_hl = QtWidgets.QHBoxLayout()
        self.stealth_hl.setObjectName("stealth_hl")
        self.stealth_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.stealth_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.stealth_cb.setText("")
        self.stealth_cb.setObjectName("stealth_cb")
        self.stealth_hl.addWidget(self.stealth_cb)
        self.stealthMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.stealthMod_lb.setObjectName("stealthMod_lb")
        self.stealth_hl.addWidget(self.stealthMod_lb)
        self.skill_fl.setLayout(16, QtWidgets.QFormLayout.LabelRole, self.stealth_hl)
        self.stealth_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.stealth_lb.setObjectName("stealth_lb")
        self.skill_fl.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.stealth_lb)
        self.survival_hl = QtWidgets.QHBoxLayout()
        self.survival_hl.setObjectName("survival_hl")
        self.survival_cb = QtWidgets.QCheckBox(self.verticalLayoutWidget_16)
        self.survival_cb.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.survival_cb.setText("")
        self.survival_cb.setObjectName("survival_cb")
        self.survival_hl.addWidget(self.survival_cb)
        self.survivalMod_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.survivalMod_lb.setObjectName("survivalMod_lb")
        self.survival_hl.addWidget(self.survivalMod_lb)
        self.skill_fl.setLayout(17, QtWidgets.QFormLayout.LabelRole, self.survival_hl)
        self.survival_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.survival_lb.setObjectName("survival_lb")
        self.skill_fl.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.survival_lb)
        self.skill_vl.addLayout(self.skill_fl)
        self.skills_horzline = QtWidgets.QFrame(self.verticalLayoutWidget_16)
        self.skills_horzline.setFrameShape(QtWidgets.QFrame.HLine)
        self.skills_horzline.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.skills_horzline.setObjectName("skills_horzline")
        self.skill_vl.addWidget(self.skills_horzline)
        self.skills_lb = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.skills_lb.setObjectName("skills_lb")
        self.skill_vl.addWidget(self.skills_lb, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.characterSheet_tb)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(590, 110, 331, 388))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.textInfo_vl = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.textInfo_vl.setContentsMargins(0, 0, 0, 0)
        self.textInfo_vl.setObjectName("textInfo_vl")
        self.textInfo_vl2 = QtWidgets.QVBoxLayout()
        self.textInfo_vl2.setObjectName("textInfo_vl2")
        self.personalityTraits_pte = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_20)
        self.personalityTraits_pte.setObjectName("personalityTraits_pte")
        self.textInfo_vl2.addWidget(self.personalityTraits_pte)
        self.personalityTraits_lb = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        self.personalityTraits_lb.setObjectName("personalityTraits_lb")
        self.textInfo_vl2.addWidget(self.personalityTraits_lb, QtCore.Qt.AlignHCenter)
        self.text_info_vl3 = QtWidgets.QVBoxLayout()
        self.text_info_vl3.setObjectName("text_info_vl3")
        self.ideals_pte = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_20)
        self.ideals_pte.setObjectName("ideals_pte")
        self.text_info_vl3.addWidget(self.ideals_pte)
        self.ideals_lb = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        self.ideals_lb.setObjectName("ideals_lb")
        self.text_info_vl3.addWidget(self.ideals_lb, QtCore.Qt.AlignHCenter)
        self.bonds_vl = QtWidgets.QVBoxLayout()
        self.bonds_vl.setObjectName("bonds_vl")
        self.bonds_pte = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_20)
        self.bonds_pte.setObjectName("bonds_pte")
        self.bonds_vl.addWidget(self.bonds_pte)
        self.bonds_lb = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        self.bonds_lb.setObjectName("bonds_lb")
        self.bonds_vl.addWidget(self.bonds_lb, QtCore.Qt.AlignHCenter)
        self.text_info_vl3.addLayout(self.bonds_vl)
        self.flaws_vl = QtWidgets.QVBoxLayout()
        self.flaws_vl.setObjectName("flaws_vl")
        self.flaws_pte = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_20)
        self.flaws_pte.setObjectName("flaws_pte")
        self.flaws_vl.addWidget(self.flaws_pte)
        self.flaws_llb = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        self.flaws_llb.setObjectName("flaws_llb")
        self.flaws_vl.addWidget(self.flaws_llb, QtCore.Qt.AlignHCenter)
        self.text_info_vl3.addLayout(self.flaws_vl)
        self.textInfo_vl2.addLayout(self.text_info_vl3)
        self.textInfo_vl.addLayout(self.textInfo_vl2)
        self.tabWidget.addTab(self.characterSheet_tb, "")
        self.spellbook_tb = QtWidgets.QWidget()
        self.spellbook_tb.setObjectName("spellbook_tb")
        self.tabWidget.addTab(self.spellbook_tb, "")
        self.inventory_tb = QtWidgets.QWidget()
        self.inventory_tb.setObjectName("inventory_tb")
        self.tabWidget.addTab(self.inventory_tb, "")
        self.notes_tb = QtWidgets.QWidget()
        self.notes_tb.setObjectName("notes_tb")
        self.tabWidget.addTab(self.notes_tb, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1109, 21))
        self.menubar.setObjectName("menubar")
        self.menuDnD_Notepad = QtWidgets.QMenu(self.menubar)
        self.menuDnD_Notepad.setObjectName("menuDnD_Notepad")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionLevel_Up = QtWidgets.QAction(MainWindow)
        self.actionLevel_Up.setObjectName("actionLevel_Up")
        self.actionFull_Screen = QtWidgets.QAction(MainWindow)
        self.actionFull_Screen.setObjectName("actionFull_Screen")
        self.actionWindowed = QtWidgets.QAction(MainWindow)
        self.actionWindowed.setObjectName("actionWindowed")
        self.menuDnD_Notepad.addSeparator()
        self.menuDnD_Notepad.addAction(self.actionNew)
        self.menuDnD_Notepad.addAction(self.actionSave)
        self.menuDnD_Notepad.addAction(self.actionSave_As)
        self.menuDnD_Notepad.addAction(self.actionLoad)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuView.addAction(self.actionFull_Screen)
        self.menuView.addAction(self.actionWindowed)
        self.menubar.addAction(self.menuDnD_Notepad.menuAction())
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DnD Notepad"))
        self.characterName_lb.setText(_translate("MainWindow", "Character Name:"))
        self.strength_lb.setText(_translate("MainWindow", "Strength"))
        self.strMod_lb.setText(_translate("MainWindow", "Str Mod"))
        self.dexterity_lb.setText(_translate("MainWindow", "Dexterity"))
        self.dexMod_lb.setText(_translate("MainWindow", "Dex Mod"))
        self.constitutuion_lb.setText(_translate("MainWindow", "Constitution"))
        self.conMod_lb.setText(_translate("MainWindow", "Con Mod"))
        self.intelligence_lb.setText(_translate("MainWindow", "Intelligence"))
        self.intMod_lb.setText(_translate("MainWindow", "Int Mod"))
        self.wisdom_lb.setText(_translate("MainWindow", "Wisdom"))
        self.wisMod_lb.setText(_translate("MainWindow", "Wis Mod"))
        self.charisma_lb.setText(_translate("MainWindow", "Charisma"))
        self.chaMod_lb.setText(_translate("MainWindow", "Cha Mod"))
        self.randomize_btn.setText(_translate("MainWindow", "Randomize"))
        self.strengthSavingThrow_cb.setText(_translate("MainWindow", "+"))
        self.strengthSavingThrow_lb.setText(_translate("MainWindow", "Strength"))
        self.dexteritySavingThrow_cb.setText(_translate("MainWindow", "+"))
        self.dexteritySavingThrow_lb.setText(_translate("MainWindow", "Dexterity"))
        self.constitutionSavingThrow_cb.setText(_translate("MainWindow", "+"))
        self.constitutionSavingThrow_lb.setText(_translate("MainWindow", "Constituion"))
        self.intelligenceSavingThrow_cb.setText(_translate("MainWindow", "+"))
        self.intelligenceSavingThrow_lb.setText(_translate("MainWindow", "Intelligence"))
        self.wisdomSavingThrow_cb.setText(_translate("MainWindow", "+"))
        self.wisdomSavingThrow_lb.setText(_translate("MainWindow", "Wisdom"))
        self.charismaSavingThrow_cb.setText(_translate("MainWindow", "+"))
        self.charismaSavingThrow_lb.setText(_translate("MainWindow", "Charisma"))
        self.savingThrows_lb.setText(_translate("MainWindow", "Saving Throws"))
        self.successes_lb.setText(_translate("MainWindow", "Successes"))
        self.failures_lb.setText(_translate("MainWindow", "Failures"))
        self.deathSaves_lb.setText(_translate("MainWindow", "Death Saves"))
        self.class_lb.setText(_translate("MainWindow", "Class:"))
        self.class_combo.setItemText(0, _translate("MainWindow", "Barbarian"))
        self.class_combo.setItemText(1, _translate("MainWindow", "Bard"))
        self.class_combo.setItemText(2, _translate("MainWindow", "Cleric"))
        self.class_combo.setItemText(3, _translate("MainWindow", "Druid"))
        self.class_combo.setItemText(4, _translate("MainWindow", "Fighter"))
        self.class_combo.setItemText(5, _translate("MainWindow", "Monk"))
        self.class_combo.setItemText(6, _translate("MainWindow", "Paladin"))
        self.class_combo.setItemText(7, _translate("MainWindow", "Ranger"))
        self.class_combo.setItemText(8, _translate("MainWindow", "Rogue"))
        self.class_combo.setItemText(9, _translate("MainWindow", "Sorcerer"))
        self.class_combo.setItemText(10, _translate("MainWindow", "Warlock"))
        self.class_combo.setItemText(11, _translate("MainWindow", "Wizard"))
        self.background_lb.setText(_translate("MainWindow", "Background:"))
        self.playerName_lb.setText(_translate("MainWindow", "Player Name:"))
        self.race_lb.setText(_translate("MainWindow", "Race:"))
        self.race_combo.setItemText(0, _translate("MainWindow", "Dwarf"))
        self.race_combo.setItemText(1, _translate("MainWindow", "Elf"))
        self.race_combo.setItemText(2, _translate("MainWindow", "Halfling"))
        self.race_combo.setItemText(3, _translate("MainWindow", "Human"))
        self.race_combo.setItemText(4, _translate("MainWindow", "Dragonborn"))
        self.race_combo.setItemText(5, _translate("MainWindow", "Gnome"))
        self.race_combo.setItemText(6, _translate("MainWindow", "Half-Elf"))
        self.race_combo.setItemText(7, _translate("MainWindow", "Half-Orc"))
        self.race_combo.setItemText(8, _translate("MainWindow", "Tiefling"))
        self.alignment_lb.setText(_translate("MainWindow", "Alignment:"))
        self.alignment_combo.setItemText(0, _translate("MainWindow", "Lawful Good"))
        self.alignment_combo.setItemText(1, _translate("MainWindow", "Neutral Good"))
        self.alignment_combo.setItemText(2, _translate("MainWindow", "Chaotic Good"))
        self.alignment_combo.setItemText(3, _translate("MainWindow", "Lawful Neutral"))
        self.alignment_combo.setItemText(4, _translate("MainWindow", "Neutral"))
        self.alignment_combo.setItemText(5, _translate("MainWindow", "Chaotic Neutral"))
        self.alignment_combo.setItemText(6, _translate("MainWindow", "Lawful Evil"))
        self.alignment_combo.setItemText(7, _translate("MainWindow", "Neutral Evil"))
        self.alignment_combo.setItemText(8, _translate("MainWindow", "Chaotic Evil"))
        self.xp_lb.setText(_translate("MainWindow", "Experience Points:"))
        self.armorClass_lb.setText(_translate("MainWindow", "Armor Class"))
        self.initiative_lb.setText(_translate("MainWindow", "Initiative"))
        self.speed_lb.setText(_translate("MainWindow", "Speed"))
        self.currentHP_lb.setText(_translate("MainWindow", "Current Hit Points"))
        self.totalHitDice_lb.setText(_translate("MainWindow", "Total Hit Dice"))
        self.hitDice_lb.setText(_translate("MainWindow", "Hit Dice"))
        self.acrobaticsMod_lb.setText(_translate("MainWindow", "+"))
        self.acrobatics_lb.setText(_translate("MainWindow", "Acrobatics (Dex)"))
        self.animalHandlingMod_lb.setText(_translate("MainWindow", "+"))
        self.animalHandling_lb.setText(_translate("MainWindow", "Animal Handling (Wis)"))
        self.arcanaMod_lb.setText(_translate("MainWindow", "+"))
        self.arcana_lb.setText(_translate("MainWindow", "Arcana (Int)"))
        self.athleticsMod_lb.setText(_translate("MainWindow", "+"))
        self.atheltics_lb.setText(_translate("MainWindow", "Atheltics (Str)"))
        self.deceptionMod_lb.setText(_translate("MainWindow", "+"))
        self.deception_lb.setText(_translate("MainWindow", "Deception (Cha)"))
        self.historyMod_lb.setText(_translate("MainWindow", "+"))
        self.history_lb.setText(_translate("MainWindow", "History (Int)"))
        self.insightMod_lb.setText(_translate("MainWindow", "+"))
        self.insight_lb.setText(_translate("MainWindow", "Insight (Wis)"))
        self.intimidationMod_lb.setText(_translate("MainWindow", "+"))
        self.intimidation_lb.setText(_translate("MainWindow", "Intimidation (Cha)"))
        self.investigationMod_lb.setText(_translate("MainWindow", "+"))
        self.investigation_lb.setText(_translate("MainWindow", "Investigation (Int)"))
        self.medicineMod_lb.setText(_translate("MainWindow", "+"))
        self.medicine_lb.setText(_translate("MainWindow", "Medicine (Wis)"))
        self.natureMod_lb.setText(_translate("MainWindow", "+"))
        self.nature_lb.setText(_translate("MainWindow", "Nature (Int)"))
        self.perceptionMod_lb.setText(_translate("MainWindow", "+"))
        self.perception_lb.setText(_translate("MainWindow", "Perception (Wis)"))
        self.performanceMod_lb.setText(_translate("MainWindow", "+"))
        self.performance_lb.setText(_translate("MainWindow", "Performance (Cha)"))
        self.persuassionMod_lb.setText(_translate("MainWindow", "+"))
        self.persuassion_lb.setText(_translate("MainWindow", "Persuassion (Cha)"))
        self.religionMod_lb.setText(_translate("MainWindow", "+"))
        self.religion_lb.setText(_translate("MainWindow", "Religion (Int)"))
        self.sleightOfHandMod_lb.setText(_translate("MainWindow", "+"))
        self.sleightOfHand_lb.setText(_translate("MainWindow", "Sleight of Hand (Dex)"))
        self.stealthMod_lb.setText(_translate("MainWindow", "+"))
        self.stealth_lb.setText(_translate("MainWindow", "Stealth (Dex)"))
        self.survivalMod_lb.setText(_translate("MainWindow", "+"))
        self.survival_lb.setText(_translate("MainWindow", "Survivial (Wis)"))
        self.skills_lb.setText(_translate("MainWindow", "Skills"))
        self.personalityTraits_lb.setText(_translate("MainWindow", "Personality Traits"))
        self.ideals_lb.setText(_translate("MainWindow", "Ideals"))
        self.bonds_lb.setText(_translate("MainWindow", "Bonds"))
        self.flaws_llb.setText(_translate("MainWindow", "Flaws"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.characterSheet_tb), _translate("MainWindow", "Character Sheet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.spellbook_tb), _translate("MainWindow", "Spellbook"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inventory_tb), _translate("MainWindow", "Inventory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.notes_tb), _translate("MainWindow", "Notes"))
        self.menuDnD_Notepad.setTitle(_translate("MainWindow", "File"))
        self.menuTest.setTitle(_translate("MainWindow", "Edit"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionLevel_Up.setText(_translate("MainWindow", "Level Up"))
        self.actionFull_Screen.setText(_translate("MainWindow", "Full Screen"))
        self.actionWindowed.setText(_translate("MainWindow", "Windowed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

